apiVersion: v2
name: vault
description: Deploy Vault

type: application

version: 0.0.1

appVersion: 1.11.3

dependencies:
  - name: vault
    version: 0.22.0
    repository: https://helm.releases.hashicorp.com
